config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :app, only: [:new]
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]


  namespace :api, defaults: {format: :json} do
    get "users/curr_user" => "users#curr_user"
    resources :listings, only: [:create, :destroy, :index, :show, :update]
    resources :users, only: [:show, :update]
    resources :listing_photos, only: [:create, :destroy, :update]
    resources :trips, only: [:show, :update, :index, :create, :destroy]
    get "listings/:id/listing_photos" => "listings#listing_photos"
  end

end

app/views/static_pages/_form.html.erb
<form class="" action="<%= action %>" method="post">
  <%= authorize_page %>
  <label for="email">
  <input
    id="email"
    type="text"
    name="user[email]"
    placeholder="email"
    value="">
  </label>
  <label for="password">
  <input
    id="password"
    type="password"
    name="user[password]"
    placeholder="password"
    value="">
  </label>
  <button>Submit</button>
</form>
<form class="guest-uesr" action="/sessions" method="post">
  <%= authorize_page %>
  <label for="email">
  <input
    class="hidden"
    id="email"
    type="text"
    name="user[email]"
    placeholder="email"
    value="guest@example.com">
  </label>
  <label for="password">
  <input
    class="hidden"
    id="password"
    type="password"
    name="user[password]"
    placeholder="password"
    value="password">
  </label>
  <button>Log in as Guest</button>
</form>

app/views/static_pages/app.html.erb
<script>
  $(document).ready(function(){
    $("body").removeClass("home-page-image");
    $('#project').html(
      nycBNB.initialize()
    );
  });
</script>

app/views/static_pages/new_session.html.erb
<div class="sign-form">
<h1>Sign In</h1>
<%= render "static_pages/form", action: "/sessions" %>
<%= link_to "Sign Up", new_user_url %>
</div>

app/views/static_pages/new_user.html.erb
<div class="sign-form">
<h1>Sign Up!</h1>
<%= render "static_pages/form", action: "/users" %>
<%= "Already a user? " %> <%= link_to "Sign In!", new_sessions_url %>
</div>